### ISSUE TITLE
FileNotFoundError on import when installed via pip

### ISSUE THREAD

**Issue by garyvdm** [exhuma/python-cluster#21]
When installing via pip, I get this error:

    >>> import cluster
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/tmp/ve/lib/python3.5/site-packages/cluster/__init__.py", line 25, in <module>
        __version__ = resource_string('cluster', 'version.txt').decode('ascii').strip()
      File "/tmp/ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1173, in resource_string
        self, resource_name
      File "/tmp/ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1605, in get_resource_string
        return self._get(self._fn(self.module_path, resource_name))
      File "/tmp/ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1728, in _get
        with open(path, 'rb') as stream:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ve/lib/python3.5/site-packages/cluster/version.txt'

When installing with `python setup.py install` from source, it works find.

pip install output:

    ve/bin/pip install cluster
    Collecting cluster
      Using cached cluster-1.3.1-py2.py3-none-any.whl
    Installing collected packages: cluster
    Successfully installed cluster-1.3.1

**Comment by wpietri** [comment]
Same issue for me under Python 3.4 installing into a virtual environment with pip. The `python setup.py install` trick didn't work for me, but `python setup.py develop` did.

**Comment by exhuma** [comment]
Should be working now (fixed in version 1.3.2 on pypi).

Give it a try. If it still breaks, give me a shout.

**Comment by wpietri** [comment]
This is no better for me. Same error despite uninstalling and installing fresh. In particular, this is the error:

```
Traceback (most recent call last):
  File "./cluster", line 4, in <module>
    from cluster import KMeansClustering
  File "[venv-path]/lib/python3.4/site-packages/cluster/__init__.py", line 25, in <module>
    __version__ = resource_string('cluster', 'version.txt').decode('ascii').strip()
  File "[venv-path]/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1161, in resource_string
    self, resource_name
  File "[venv-path]/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1589, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "[venv-path]/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1712, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '[venv-path]/lib/python3.4/site-packages/cluster/version.txt'

```

 When I download this file:

https://pypi.python.org/packages/py2.py3/c/cluster/cluster-1.3.2-py2.py3-none-any.whl

this is what I see:

```
$ unzip cluster-1.3.2-py2.py3-none-any.whl
Archive:  cluster-1.3.2-py2.py3-none-any.whl
 extracting: cluster/cluster.py      
 extracting: cluster/matrix.py       
 extracting: cluster/linkage.py      
 extracting: cluster/__init__.py     
 extracting: cluster/util.py         
 extracting: cluster/method/base.py  
 extracting: cluster/method/kmeans.py  
 extracting: cluster/method/hierarchical.py  
 extracting: cluster/method/__init__.py  
 extracting: cluster-1.3.2.dist-info/DESCRIPTION.rst  
 extracting: cluster-1.3.2.dist-info/metadata.json  
 extracting: cluster-1.3.2.dist-info/top_level.txt  
 extracting: cluster-1.3.2.dist-info/WHEEL  
 extracting: cluster-1.3.2.dist-info/METADATA  
 extracting: cluster-1.3.2.dist-info/RECORD  
```

**Comment by exhuma** [comment]
Args... that teaches me releasing without testing... I was convinced I knew what I was doing...

hang on a second... I'm fairly sure I know what's going on...

**Comment by exhuma** [comment]
Alright... give it a go with 1.3.3

**Comment by wpietri** [comment]
That fixes it. Thanks!
