### ISSUE TITLE
Proper visualisation of clusters

### ISSUE THREAD

**Issue by 1kastner** [exhuma/python-cluster#24]
I currently visualize the output of hierarchical clustering this way:

    cluster = HierarchicalClustering(
        [custom_time_series_object_1, custom_time_series_object_2, ...],
        lambda x, y: compare_time_series(x, y, "temperature")
    )
    cluster.cluster()
    cluster._data[0].display()

Somehow this feels a bit dirty as the underscore indicates that it is a private member. Is there a better, more sophisticated way how to do this? I somehow want to have an informative dendogram.

**Comment by exhuma** [comment]
I am currently unaware of a cleaner way to accomplish this. I agree that it should be a public method on the top-level object. Something like `cluser.display()` in your example.

I'll flag it as enhancement.

For now, don't worry using is as such. I currently have not a lot of spare time to work on this project so the functionality is unlikely to disappear. I think a good solution would be to simply implement the "display" function as a simple delegate to the function you are using right now. I'll get to it once I have more time. Unless you want to submit a PR ;)

**Comment by 1kastner** [comment]
Closed with #25

**Comment by exhuma** [comment]
By the way, I also pushed it to pypi as 1.4.0.

Thanks for the PR :)

**Comment by 1kastner** [comment]
Oh nice :)
